### ISSUE TITLE
 Doesn't handle promises that are functions

### ISSUE THREAD

**Issue by chocolateboy** [sindresorhus/p-is-promise#6]
> “thenable” is an object **or function** that defines a then method.

-- https://promisesaplus.com/

So `typeof input === 'object'` is incomplete/incorrect:

https://github.com/sindresorhus/p-is-promise/blob/cda35a513bda03f977ad5cde3a079d237e82d7ef/index.js#L7

**Comment by sindresorhus** [comment]
Not technically incorrect as it *does* correctly check for a "promise". It doesn't advertize it checks for "thenables". That being said, I agree, it does make sense to support this.
