### ISSUE TITLE
Genuine question

### ISSUE THREAD

**Issue by foxt** [sindresorhus/p-is-promise#9]
Why?

 Would it be easier for all, reduce bundle sizes and over all development complexity if instead of being a whole NPM package, it was just a README that said

```
To check if a value is a promise, simply do the following:
    value instanceof Promise
```

Even works on Node 11 (probably)!

**Comment by sindresorhus** [comment]
You are indirectly proving why it's useful for this to be a package. `value instanceof Promise` is not the correct way to check if something is a promise. It will miss out on custom Promise implementations or if the promise comes from a different realm (for example, iframe or Node.js `vm` module).

Nothing stops you from just copy-pasting the code in this package into your project though. It's provided as a package for convenience.
